openapi: 3.0.3
info:
  title: Peerplay CR Server - Private API
  version: 1.0.0
  description: API to manage the private settings of Peerplay CR Server (Not Opened to Internet)
servers:
  - url: http://localhost:5986
    description: Local server
tags:
  - name: /filter
    description: Get or Manage Filter
  - name: /network/general
    description: Get or Manage general network
  - name: /network/router
    description: Get and manage router
paths:
  /filter/filter_settings:
    get:
      tags:
        - /filter
      summary: Get filter settings
      description: Returns the current filter settings for the private router API.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  output:
                    type: object
                    properties:
                      network_type:
                        type: string
                      password:
                        type: string
                      strict_mode:
                        type: boolean
        "400":
          description: Bad Request
  /filter/filter_settings/network_type:
    post:
      tags:
        - /filter
      summary: Set filter settings (Network Type)
      description: Change the network type.
      parameters:
        - in: query
          name: method
          description: Name of the method to change the NETWORK_TYPE value of the filter settings
          schema:
            type: string
            nullable: false
            default: "NETWORK_TYPE"
            readOnly: true
          required: true
          x-ui-name: "disabled-input"
          x-ui-disabled: true
        - in: query
          name: network_type
          description: >-
            This property represents the type of network used by the user and if it allow other type of network,
            The possible values are:
            - NT1: All users including you are connected to the Internet using Fiber Optic.
            - NT2: All users including you are connected to the Internet using ADSL.
            - NT3: All users including you are connected to the Internet using Mobile Network.
            - ANY: All users including you accept all
          schema:
            type: string
            enum:
              - NT1
              - NT2
              - NT3
              - ANY
            maxLength: 3
          required: true
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
  /filter/filter_settings/password_key:
    post:
      tags:
        - /filter
      summary: Set filter settings (Change Network Key for a Password Key)
      description: Change the network key of the filter settings by a Password Key
      parameters:
        - in: query
          name: method
          description: Name of the method to change the NETWORK_TYPE value of the filter settings
          schema:
            type: string
            nullable: false
            default: "NETWORK_KEY"
            readOnly: true
          required: true
        - in: query
          name: network_key
          description: This property represents the password_key used for filter the network (used for private / party networks or championships)
          schema:
            type: string
            maxLength: 36
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
  /filter/filter_settings/geographic_key:
    post:
      tags:
        - /filter
      summary: Set filter settings (Change Network Key for a Geographic Key)
      description: Change the network key of the filter settings by a Geographic Key
      parameters:
        - in: query
          name: method
          description: Name of the method to change the NETWORK_KEY value of the filter settings by a geographic key
          schema:
            type: string
            nullable: false
            default: "GEOGRAPHIC_KEY"
            readOnly: true
          required: true
        - in: query
          name: geographic_network_type
          description: >-
            Choose Geographic Key Type
            - WORLD: Connect to the Global Public Network
            - CONTINENTAL: Connect to your continental Public Network
            - COUNTRY: Connect to your country Public Network
            - REGIONAL: Connect to your regional Public Network
            - DEPARTMENTAL: Connect to your deparmental Public Network
            - LOCAL: Connect to your local Public Network
          schema:
            type: string
            enum:
              - WORLD
              - CONTINENTAL
              - COUNTRY
        - in: query
          name: lattitude
          description: This property represents the lattitude of your GPS Position
          schema:
            type: string
        - in: query
          name: longitude
          description: This property represents the longitude of your GPS Position
          schema:
            type: string
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
  /filter/filter_settings/strict_mode:
    post:
      tags:
        - /filter
      summary: Set filter settings (Strict Mode)
      description: Enable or Disable Strict Mode (Filter if the machine running the peerplay server is connected via wifi or ethernet)
      parameters:
        - in: query
          name: method
          description: Name of the method to change the STRICT_MODE value of the filter settings
          schema:
            type: string
            nullable: false
            default: "STRICT_MODE"
            readOnly: true
          required: true
        - in: query
          name: strict_mode
          description: >-
            This property change the status of the strict mode
            The possible values are:
            - true: All users (including you) have connected their computers to the internet in the same way (Wi-Fi OR Ethernet)
            - false: All users (including you) ignore the way they have connected their computers to the internet and accept all
          schema:
            type: boolean
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
  /network/general/network_info:
    get:
      tags:
        - /network/general
      summary: Get network information
      description: Returns the current active network information for the private router API.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  output:
                    type: string
        "400":
          description: Bad Request

  /network/general/status:
    get:
      tags:
        - /network/general
      summary: Get server status
      description: Returns the current status of the private router API.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  online:
                    type: integer
                    description: Number of online servers in the network
                  p2p_relay_ip:
                    type: string
                    description: P2P relay IP address
                  external_ip:
                    type: string
                    description: External IP address
        "400":
          description: Bad Request
  /network/router/logs:
    get:
      tags:
        - /network/router
      summary: Get router logs
      description: Returns the logs for the private router API.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
